Repository SJang1/korea-covid-19-remaining-vaccine-macro, pull requests merged in 2021-07, with the labels that each got.

#184 코드 리팩토링 및 PEP 8에 맞지 않는 코드 변경
  vaccine-run-kakao.py
Labels: enhancement

#382 Revert "ci: Force x86 with own v4.3 bootloader on windows"
  .github/workflows/package.yml
Labels: CI

#383 ci: Pin pyinstaller as include in repository
  .github/workflows/package.yml
  .github/workflows/pyinstaller.yml
  pyinstaller/pyinstaller-4.4-py3-none-any.whl
  pyinstaller/pyinstaller-4.4.tar.gz
Labels: CI

#420 feat: Play sound on shutdown
  .github/workflows/package.yml
  requirements.txt
  vaccine-run-kakao.py
  xylophon.mp3
Labels: enhancement

#528 Workaround to preserve file permission on macOS
  .github/workflows/package.yml
Labels: CI

#582 ci: Release the program with action
  .github/workflows/package.yml
  .github/workflows/virustotal.yml
  .gitignore
Labels: CI

#581 ci: add windows build cache
  .github/workflows/package.yml
Labels: CI

#625 ci: Python lint
  .github/workflows/lint.yml
  .prospector.yaml
  vaccine-run-kakao.py
Labels: CI

#670 PEP8 포맷팅, 불필요한 변수 선언 삭제, Readme 업데이트
  README.md
  vaccine-run-kakao.py
Labels: documentation, enhancement

#689 chore: Update READMD.md [skip ci]
  README.md
Labels: documentation

#690 Check input coordinates
  vaccine-run-kakao.py
Labels: enhancement

#696 feat: cookie file config
  .gitignore
  vaccine-run-kakao.py
Labels: enhancement

#623 github actions 맥 빌드시 캐싱
  .github/workflows/package.yml
Labels: CI
